##############################################################################
# Automations for handling toggle state BUTTONs on page 6
automation:
  #Set font and text for toggle BUTTONs on device connection
  - alias: hasp_plate01_p6_ToggleInit
    trigger:
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
     
    action:
    #Change payload (BUTTON4) to the name for b4
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[10].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[10].txt'
        payload: '"BUTTON4"'  
    #Change payload (b5) to the name for b5
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[11].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[11].txt'
        payload: '"BUTTON5"'
    #Change payload (BUTTON6) to the name for b6
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[12].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[12].txt'
        payload: '"BUTTON6"'
    #Change payload (BUTTON7) to the name for b7
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[13].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[13].txt'
        payload: '"BUTTON7"'
    #Change payload (BUTTON8) to the name for b8
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[14].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[14].txt'
        payload: '"BUTTON8"'
    #Change payload (BUTTON9) to the name for BUTTON9
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[15].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[15].txt'
        payload: '"BUTTON9"'


  # Toggle BUTTON4 when p[6].b[4] pressed
  - alias: hasp_plate01_p6_Toggle1
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[6].b[4]'
      payload: 'ON'
    action:
    - service: homeassistant.toggle
      entity_id: switch.YOUR_ENTITY1
      
  # Toggle BUTTON5 when p[6].b[5] pressed
  - alias: hasp_plate01_p6_Toggle2
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[6].b[5]'
      payload: 'ON'
    action:
    - service: homeassistant.toggle
      entity_id: switch.YOUR_ENTITY2

  # Toggle BUTTON6 when p[6].b[6] pressed
  - alias: hasp_plate01_p6_Toggle3
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[6].b[6]'
      payload: 'ON'
    action:
    - service: homeassistant.toggle
      entity_id: switch.YOUR_ENTITY3
      
   # Toggle BUTTON7 when p6.b7 pressed
  - alias: hasp_plate01_p6_Toggle4
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[6].b[7]'
      payload: 'ON'
    action:
    - service: homeassistant.toggle
      entity_id: switch.YOUR_ENTITY4
      
   # Toggle BUTTON8 when p6.b8
  - alias: hasp_plate01_p6_Toggle5
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[6].b[8]'
      payload: 'ON'
    action:
    - service: homeassistant.toggle
      entity_id: switch.YOUR_ENTITY5
    
    # Toggle BUTTON9 p6.b9
  - alias: hasp_plate01_p6_Toggle6
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[6].b[9]'
      payload: 'ON'
    action:
    - service: homeassistant.toggle
      entity_id: switch.YOUR_ENTITY6
          
      
  # Toggle colors/icon on p[6].b[4] when BUTTON4 changes
  - alias: hasp_plate01_p2_ToggleColor1
    trigger:
    - platform: state
      entity_id: switch.YOUR_ENTITY1
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[10].pco'
        payload_template: >-
          {% if states.switch.YOUR_ENTITY1 == "on" -%}
            {{ states.input_number.hasp_plate01_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedforegroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[6].b[4].picc'
        payload_template: >-
          {% if states.switch.YOUR_ENTITY1.state == "on" -%}
            {{ 1 }}
          {%- else -%}
            {{ 2 }}
          {%- endif %}

  # Toggle colors on p[6].b[5] when BUTTON5 changes
  - alias: hasp_plate01_p6_ToggleColor2
    trigger:
    - platform: state
      entity_id: switch.YOUR_ENTITY2
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[11].pco'
        payload_template: >-
          {% if states.switch.YOUR_ENTITY2.state == "on" -%}
            {{ states.input_number.hasp_plate01_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedforegroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[6].b[5].picc'
        payload_template: >-
          {% if states.switch.YOUR_ENTITY2.state == "on" -%}
            {{ 1 }}
          {%- else -%}
            {{ 2 }}
          {%- endif %}

  # Toggle colors on p[6].b[6] when BUTTON6 changes
  - alias: hasp_plate01_p6_ToggleColor3
    trigger:
    - platform: state
      entity_id: light.switch.YOUR_ENTITY3
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[12].pco'
        payload_template: >-
          {% if states.light.switch.YOUR_ENTITY3.state == "on" -%}
            {{ states.input_number.hasp_plate01_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedforegroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[6].b[6].picc'
        payload_template: >-
          {% if states.light.switch.YOUR_ENTITY3.state == "on" -%}
            {{ 1 }}
          {%- else -%}
            {{ 2 }}
          {%- endif %}
          
  # Toggle colors on p[6].b[7] when BUTTON7 changes
  - alias: hasp_plate01_p7_ToggleColor3
    trigger:
    - platform: state
      entity_id: switch.YOUR_ENTITY4
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[13].pco'
        payload_template: >-
          {% if states.light.switch.YOUR_ENTITY4.state == "on" -%}
            {{ states.input_number.hasp_plate01_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedforegroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[6].b[7].picc'
        payload_template: >-
          {% if states.light.switch.YOUR_ENTITY4 == "on" -%}
            {{ 1 }}
          {%- else -%}
            {{ 2 }}
          {%- endif %}
   
  # Toggle colors on p[6].b[8] when BUTTON8 changes
  - alias: hasp_plate01_p8_ToggleColor3
    trigger:
    - platform: state
      entity_id: switch.YOUR_ENTITY5
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[14].pco'
        payload_template: >-
          {% if states.light.switch.YOUR_ENTITY5.state == "on" -%}
            {{ states.input_number.hasp_plate01_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedforegroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[6].b[8].picc'
        payload_template: >-
          {% if states.light.switch.YOUR_ENTITY5.state == "on" -%}
            {{ 1 }}
          {%- else -%}
            {{ 2 }}
          {%- endif %}
          
  # Toggle colors on p[6].b[9] when BUTTON9 changes
  - alias: hasp_plate01_p9_ToggleColor3
    trigger:
    - platform: state
      entity_id: switch.YOUR_ENTITY6
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[6].b[15].pco'
        payload_template: >-
          {% if states.light.switch.YOUR_ENTITY6.state == "on" -%}
            {{ states.input_number.hasp_plate01_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_plate01_unselectedforegroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[6].b[9].picc'
        payload_template: >-
          {% if states.light.switch.YOUR_ENTITY6.state == "on" -%}
            {{ 1 }}
          {%- else -%}
            {{ 2 }}
          {%- endif %}
     