##############################################################################
# Automations to display the weather forecast and current temp on page 3

automation:
  # Display weather details on page 3 when weather updates or on HASP init
  - alias: hasp_plate01_p4_Weather
    trigger:
    - platform: state
      entity_id: sensor.xiaomi_mijia_mean
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
    - platform: homeassistant
      event: start
    condition:
    - condition: state
      entity_id: 'binary_sensor.plate01_connected'
      state: 'on'
    action:
    # Textfield Temp Inside
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[7].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[7].txt'
        payload_template: '"In"'
    # Inside Temperature (Add your Temperature Sensor Entity in payload_template)
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[6].font'
        payload: '6'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[6].txt'
        payload_template: '"{{ states.sensor.xiaomi_mijia_mean.state }}°C"'

    # Inside Humidity (Add your Humidity Sensor Entity in payload_template)
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[8].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[8].txt'
        payload_template: '"{{ states.sensor.mijia_1_humidity.state }}%"'

# Forecast
# Textfield of "now" Weather Icon
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[12].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[12].txt'
        payload_template: '"now"'
# Weather Icon Now
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[4].b[9].pic'
        payload_template: >-
          {% if states.sensor.dark_sky_icon_0d.state == "clear-day" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon_0d.state == "clear-night" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon_0d.state == "rain" -%}
            {{ 13 }}
          {%- elif states.sensor.dark_sky_icon_0d.state == "partly-cloudy-day" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon_0d.state == "partly-cloudy-night" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon_0d.state == "cloudy" -%}
            {{ 12 }}
          {%- elif states.sensor.dark_sky_icon_0d.state == "fog" -%}
            {{ 17 }}
          {%- elif states.sensor.dark_sky_icon_0d.state == "snow" -%}
            {{ 16 }}
          {%- elif states.sensor.dark_sky_icon_0d.state == "sleet" -%}
            {{ 16 }}
          {%- endif %}

# Textfield for 24h Weather Icon
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[13].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[13].txt'
        payload_template: '"24h"'
  #Icon Weather 24h  
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[10].font'
        payload: '12'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[4].b[10].pic'
        payload_template: >-
          {% if states.sensor.dark_sky_icon_1d.state == "clear-day" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon_1d.state == "clear-night" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon_1d.state == "rain" -%}
            {{ 13 }}
          {%- elif states.sensor.dark_sky_icon_1d.state == "partly-cloudy-day" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon_1d.state == "partly-cloudy-night" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon_1d.state == "cloudy" -%}
            {{ 12 }}
          {%- elif states.sensor.dark_sky_icon_1d.state == "fog" -%}
            {{ 17 }}
          {%- elif states.sensor.dark_sky_icon_1d.state == "snow" -%}
            {{ 16 }}
          {%- elif states.sensor.dark_sky_icon_1d.state == "sleet" -%}
            {{ 16 }}
          {%- endif %}

# Textfield for 48h Weather Icon
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[14].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[4].b[14].txt'
        payload_template: '"48h"'
# 48h Weather Icon
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[4].b[11].pic'
        payload_template: >-
          {% if states.sensor.dark_sky_icon_2d.state == "clear-day" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon_2d.state == "clear-night" -%}
            {{ 20 }}
          {%- elif states.sensor.dark_sky_icon_2d.state == "rain" -%}
            {{ 13 }}
          {%- elif states.sensor.dark_sky_icon_2d.state == "partly-cloudy-day" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon_2d.state == "partly-cloudy-night" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon_2d.state == "cloudy" -%}
            {{ 12 }}
          {%- elif states.sensor.dark_sky_icon_2d.state == "fog" -%}
            {{ 19 }}
          {%- elif states.sensor.dark_sky_icon_2d.state == "snow" -%}
            {{ 17 }}
          {%- elif states.sensor.dark_sky_icon_2d.state == "sleet" -%}
            {{ 18 }}
          {%- endif %}

