##############################################################################
# Automations to display the weather forecast and current temp on page 3

automation:
  # Display weather details on page 3 when weather updates or on HASP init
  - alias: hasp_plate01_p3_Weather
    trigger:
    - platform: state
      entity_id: sensor.esszimmer_temperatur
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
    - platform: homeassistant
      event: start
    condition:
    - condition: state
      entity_id: 'binary_sensor.plate01_connected'
      state: 'on'
    action:
    # Textfield 
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[68].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[8].txt'
        payload_template: '"Temp"'
    # Outside Weather
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[6].font'
        payload: '6'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[6].txt'
        payload_template: '"{{ states.sensor.dark_sky_temperature.state }}°C"'

    # Out Humidity
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[9].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[9].txt'
        payload_template: '"{{ states.sensor.dark_sky_humidity.state }}%"'



#    # Forecast
#    - service: mqtt.publish
#      data:
#        topic: 'hasp/plate01/command/p[3].b[8].font'
#        payload_template: '{% if states.weather.met_no.state|length <= 6 -%}3{% elif (states.weather.met_no.state|length > 6) and (states.weather.met_no.state|length <= 10) %}2{% elif (states.weather.met_no.state|length > 10) and (states.weather.met_no.state|length <= 15) %}1{% else %}0{%- endif %}'
#    - service: mqtt.publish
#      data:
#        topic: 'hasp/plate01/command/p[3].b[8].txt'
#        payload_template: '"{{states.weather.met_no.state|wordwrap(20, wrapstring="\\r")|title}}"'

         # Forecast
    #- service: mqtt.publish
    #  data:
    #    topic: 'hasp/plate01/command/p[3].b[8].font'
    #    payload_template: '{% if states.sensor.dark_sky_summary.state|length <= 6 -%}2{% elif (states.sensor.dark_sky_summary.state|length > 6) and (states.sensor.dark_sky_summary.state|length <= 10) %}1{% elif (states.sensor.dark_sky_summary.state|length > 10) and (states.sensor.dark_sky_summary.state|length <= 15) %}0{% else %}0{%- endif %}'
    #- service: mqtt.publish
    #  data:
    #    topic: 'hasp/plate01/command/p[3].b[8].txt'
    #    payload_template: '"{{ states.sensor.dark_sky_summary.state }}"'

# Forecast
  # Heute
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[16].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[16].txt'
        payload_template: '"tdy"'
# Icon Now
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[3].b[13].pic'
        payload_template: >-
          {% if states.sensor.dark_sky_icon.state == "clear-day" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon.state == "clear-night" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon.state == "rain" -%}
            {{ 13 }}
          {%- elif states.sensor.dark_sky_icon.state == "partly-cloudy-day" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon.state == "partly-cloudy-night" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon.state == "cloudy" -%}
            {{ 12 }}
          {%- elif states.sensor.dark_sky_icon.state == "fog" -%}
            {{ 17 }}
          {%- elif states.sensor.dark_sky_icon.state == "snow" -%}
            {{ 16 }}
          {%- elif states.sensor.dark_sky_icon.state == "sleet" -%}
            {{ 16 }}
          {%- endif %}

  # Morgen
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[17].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[17].txt'
        payload_template: '"1d"'
    #Icon  MOrgen  
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[14].font'
        payload: '12'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[3].b[14].pic'
        payload_template: >-
          {% if states.sensor.dark_sky_icon.state == "clear-day" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon.state == "clear-night" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon.state == "rain" -%}
            {{ 13 }}
          {%- elif states.sensor.dark_sky_icon.state == "partly-cloudy-day" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon.state == "partly-cloudy-night" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon.state == "cloudy" -%}
            {{ 12 }}
          {%- elif states.sensor.dark_sky_icon.state == "fog" -%}
            {{ 17 }}
          {%- elif states.sensor.dark_sky_icon.state == "snow" -%}
            {{ 16 }}
          {%- elif states.sensor.dark_sky_icon.state == "sleet" -%}
            {{ 16 }}
          {%- endif %}

  # 2d
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[18].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[18].txt'
        payload_template: '"2d"'

    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[3].b[15].pic'
        payload_template: >-
          {% if states.sensor.dark_sky_icon.state == "clear-day" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon.state == "clear-night" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon.state == "rain" -%}
            {{ 13 }}
          {%- elif states.sensor.dark_sky_icon.state == "partly-cloudy-day" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon.state == "partly-cloudy-night" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon.state == "cloudy" -%}
            {{ 12 }}
          {%- elif states.sensor.dark_sky_icon.state == "fog" -%}
            {{ 17 }}
          {%- elif states.sensor.dark_sky_icon.state == "snow" -%}
            {{ 16 }}
          {%- elif states.sensor.dark_sky_icon.state == "sleet" -%}
            {{ 16 }}
          {%- endif %}
    

#######################################
##                                   ##
##           Weather Icons           ##
##                                   ##
#######################################

##---- Icons ----##

# cloudy: pic12
# rainy:  pic13
# partly_cloud: pic14
# sunny: pic15
# snow: pic16
# fog: pic17
# sleet: ?
# wind: ?

##---- Buttons & Textfields ----##
# today_text:16
# today_icon: 13

# 1d_text:17
# tomorrow_icon: 14

# 2d_text: 18
# 2d_icon: 15

morrow_icon: 14

# 2d_text: 18
# 2d_icon: 15

 15
   ##
#######################################

##---- Icons ----##

# cloudy: pic12
# rainy:  pic13
# partly_cloud: pic14
# sunny: pic15
# snow: pic16
# fog: pic17
# sleet: ?
# wind: ?

##---- Buttons & Textfields ----##
# today_text:16
# today_icon: 13

# 1d_text:17
# tomorrow_icon: 14

# 2d_text: 18
# 2d_icon: 15
5
icon: 15


