##############################################################################
# Automations to set colors on HASP Page 8

#automation:
#  - alias: hasp_plate01_p8_ColorConfig
#    trigger:
#    - platform: state
#      entity_id: 'binary_sensor.plate01_connected'
#      to: 'on'
#    - platform: homeassistant
#      event: start
#    - platform: state
#      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
#    - platform: state
#      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
#    - platform: state
#      entity_id: input_number.hasp_plate01_selectedforegroundcolor
#    - platform: state
#      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
#    action:
#    - service: mqtt.publish
#      data:
#        topic: 'hasp/plate01/command/json'
#        payload_template: >-
#          [{%- for i in range(4,9) -%}"p[8].b[{{i}}].pco={{ states.input_number.hasp_plate01_selectedforegroundcolor.state|int }}",{%- endfor -%}
#          {%- for i in range(4,9) -%}"p[8].b[{{i}}].bco={{ states.input_number.hasp_plate01_selectedbackgroundcolor.state|int }}",{%- endfor -%}
#          {%- for i in range(4,9) -%}"p[8].b[{{i}}].pco2={{ states.input_number.hasp_plate01_unselectedforegroundcolor.state|int }}",{%- endfor -%}
#          {%- for i in range(4,9) -%}"p[8].b[{{i}}].bco2={{ states.input_number.hasp_plate01_unselectedbackgroundcolor.state|int }}",{%- endfor -%}]
#    - service: mqtt.publish
#      data:
#        topic: 'hasp/plate01/command/json'
#        payload_template: >-
#          ["p[8].b[9].pco={{ states.input_number.hasp_plate01_unselectedforegroundcolor.state|int }}",
#          "p[8].b[9].bco={{ states.input_number.hasp_plate01_unselectedbackgroundcolor.state|int }}"]